/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amtaugestor;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import tablas.MiModeloTablaArticulos;

/**
 *
 * @author mauro
 */
public class SaldosSocios extends javax.swing.JInternalFrame {
    private ArrayList listado=new ArrayList();
    /**
     * Creates new form SaldosSocios
     */
    public SaldosSocios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiModeloTablaArticulos modelo=new MiModeloTablaArticulos();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Administracion de Saldos de Socios");

        Socios socio=new Socios();
        listado=socio.listar();
        Iterator list=listado.listIterator();
        jTable1.setModel(modelo);
        modelo.addColumn("NUMERO DE SOCIO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("SALDO");
        modelo.addColumn("ACTUAL");
        modelo.addColumn("AJUSTE");
        modelo.addColumn("SOLICITUD");
        Object[] fila=new Object[6];
        while(list.hasNext()){
            socio=(Socios)list.next();
            fila[0]=socio.getNumeroCliente();
            fila[1]=socio.getApellido();
            fila[2]=socio.getSaldo();
            fila[3]=0.00;
            fila[4]=0.00;
            fila[5]=socio.getNumeroSolicitud();
            modelo.addRow(fila);
        }
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int renglon=this.jTable1.rowAtPoint(evt.getPoint());
        System.out.println("el renglon es "+renglon);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total=this.jTable1.getRowCount();
        System.out.println("TOTAL DE RENGLONES "+total);
        Double saldo=0.00;
        Double actual=0.00;
        Double ajuste=0.00;
        for(int i=0;i < total;i++){
            saldo=Double.parseDouble(String.valueOf(this.jTable1.getValueAt(i,2)));
            System.err.println("saldos "+saldo+" renglon "+i);
            actual=Double.parseDouble(String.valueOf(this.jTable1.getValueAt(i,3)));
            
            if(actual > 0){
                ajuste=actual - saldo;
                this.jTable1.setValueAt(ajuste,i, 4);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ss="insert into amtau_cobranza (numeroCobrador,numeroCliente,numeroDePlan,montoCobrado,tipoMovimiento,montoACobrar,cuotaNumero) values ";
        int total=this.jTable1.getRowCount();
        Double ajuste=0.00;
        Integer numeroCliente=0;
        for(int i=0;i < total;i++){
            ajuste=Double.parseDouble(String.valueOf(this.jTable1.getValueAt(i,4)));
            
            if(ajuste > 0){
                numeroCliente=Integer.parseInt(String.valueOf(this.jTable1.getValueAt(i,0)));
                ss+="(1,"+numeroCliente+",1,"+ajuste+",3,0,'1/1'),";
                //this.jTable1.setValueAt(ajuste,i, 4);
            }
        }
        int tama=ss.length();
        tama=tama -1;
        ss=ss.substring(0,tama);
        System.out.println("SENTENCIA "+ss);
        Socios socio=new Socios();
        try {
            socio.movimientoDeAjusteDeSaldo(ss);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SaldosSocios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SaldosSocios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
